version: '3.1'
services:
  db:
    # platform: linux/amd64
    image: mysql:latest
    container_name: local-db
    ports:
      - "3306:3306"
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - elk

  redis:
    image: redis:alpine
    command: redis-server
    container_name: redis_boot
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
    networks:
      - elk

  spring:
    container_name: voyager-backend-dev
    build: .
    ports:
      - "8080:8080"
    environment:
      - "PROFILE=docker-prod"
    volumes:
      - ./log:/home/spring-docker/deploy/log
    depends_on:
      - db
      - redis
    networks:
      - elk

networks:
  elk: