# resource upload path
attachFileLocation: file://${HOME}/attach-files
#uploadDir: /home/ubuntu/img/
uploadDir: /Users/juwon/IdeaProjects/teamMVP/img/
server:
  port: 8080
spring:
  servlet:
    multipart:
     maxFileSize: 10MB
     maxRequestSize: 10MB
  profiles:
    include: secure
    active: local
  #  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password:
#    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      format_sql: true
    show_sql: true
logging.level:
  org.hibernate.SQL: debug

logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml

decorator:
  datasource:
    p6spy:
      enable-logging: true # 운영시 false로 변경