# resource upload path
attachFileLocation: file://${HOME}/attach-files
uploadDir: "/home/ec2-user/img/"
server:
  port: 8080
spring:
  servlet:
    multipart:
    maxFileSize: 10MB
    maxRequestSize: 10MB
  profiles:
    include: API-KEY
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      format_sql: true
#    show_sql: true
logging.level:
  org.hibernate.SQL: debug