# resource upload path
attachFileLocation: file://${HOME}/attach-files

spring.redis:
  host: localhost
  port: 6379

spring:
  profiles:
    active: dev # 활성화 시킬 프로필
    #include: secure, 추후에 group 에 auth 추가 예정
    group:
      prod: prod, prod2
      dev: dev, dev2
      test: test

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
      #location: /data/upload_tmp