# resource upload path
attachFileLocation: file://${HOME}/attach-files

spring:
  profiles:
    active: prod # 활성화 시킬 프로필
    #include: secure, 추후에 group 에 auth 추가 예정
    group:
      prod: prod, prod2
      dev: dev, dev2
      test: test
      docker: docker, docker-prod
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
      #location: /data/upload_tmp
# springdoc:
#   api-docs:
#     path: /spring/v3/api-docs
# server:
#   servlet:
#     context-path: /spring
#   tomcat:
#     basedir: .                              # access log를 저장할 base directory 지정
#     accesslog:
#       enabled: true                         # access log 저장 여부 (default: false)
#       directory: logs                       # access log를 저장할 상세 directory (base directory에 기반한) (default: logs)
#       pattern: '%h %l %u %t "%r" %s %b %D'  # access log 출력 패턴
#       prefix: access                        # access log 파일이름 prefix
#       suffix: .log                          # access log 파일이름 suffix (확장자 포함)
#       rotate: true                          # access log rotation 여부
#       rename-on-rotate: true                # rotation 시, 새로운 이름 지정 여부 (rotate 될 때의 날짜명이 로그 파일이름에 찍힘)
server:
  forward-headers-strategy: framework