# resource upload path
attachFileLocation: file://${HOME}/attach-files
#attachFileUri: /images/**
server:
 port: 8080
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
spring:
 servlet:
   multipart:
    maxFileSize: 10MB
    maxRequestSize: 10MB
 profiles:
  include: API-KEY